name: bikes_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_rating_bar: ^4.0.0
  flutter:
    sdk: flutter  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  lint: ^1.5.3
  introduction_screen: ^2.1.0
  pin_code_fields: ^7.3.0
  flutter_svg: ^0.22.0
  intl_phone_field:
    git:
      url: git://github.com/vanshg395/intl_phone_field.git
      ref: master
  flutter_multi_formatter: ^2.3.2
  circular_profile_avatar:
    git:
      url: git://github.com/ch-muhammad-adil/flutter-plugin-circular_profile_avatar.git
      ref: master
  get: ^4.3.8
  
  # support ui
  carousel_slider: ^4.0.0

  # flutter hook
  flutter_hooks: ^0.18.0
  # open link
  url_launcher: ^6.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # use everything in assets folder
    - assets/images/
    - assets/fonts/
    - assets/gifs/


  fonts:
    - family: SVN Product Sans
      fonts:
        - asset: assets/fonts/SVNProductSans_Regular.ttf
        - asset: assets/fonts/SVNProductSans_Italic.ttf
          style: italic
        - asset: assets/fonts/SVNProductSans_Bold.ttf
          weight: 700
        - asset: assets/fonts/SVNProductSans_Bold_Italic.ttf
          style: italic
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
