name: bikes_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_rating_bar: ^4.0.0
  flutter:
    sdk: flutter  
  email_validator: ^2.0.1
  camera:
  path_provider:
  path:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  lint: ^1.6.0
  introduction_screen: ^2.1.0

  flutter_svg: ^0.22.0
  intl_phone_field:
    git:
      url: git://github.com/vanshg395/intl_phone_field.git
      ref: master
  flutter_multi_formatter: ^2.3.5
  circular_profile_avatar:
    git:
      url: git://github.com/ch-muhammad-adil/flutter-plugin-circular_profile_avatar.git
      ref: master
  get:
    git:
      url: git://github.com/jonataslaw/getx.git
      ref: master
  
  pin_code_fields: ^7.3.0

  json_annotation: ^4.0.1
  
  # support ui
  carousel_slider: ^4.0.0
  awesome_dialog: ^2.1.1
  
  # flutter hook
  flutter_hooks: ^0.18.0
  # open link
  url_launcher: ^6.0.11
  intl: ^0.17.0
  flutter_screenutil: ^5.0.0+2

  # firebase service
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  google_sign_in: ^5.1.1
  firebase_messaging: ^11.1.0
  firebase_analytics: ^8.3.4
  firebase_database: ^8.1.0

  # api
  retrofit: ^2.0.1
  dio: ^4.0.0

  # di
  get_it: ^7.2.0
  injectable: ^1.5.0

  # local storage
  shared_preferences: ^2.0.8
  infinite_scroll_pagination: ^3.1.0
  flutter_logs: ^2.1.4
  device_info_plus: ^3.1.0
  location: ^4.3.0
  back_pressed: ^0.0.2
  google_maps_flutter: ^2.1.0
  momo_vn: ^2.0.1
  pointycastle: ^3.4.0
  rsa_encrypt: ^2.0.0
  asn1lib: ^1.0.3
  random_string: ^2.3.1
  flutter_polyline_points: ^1.0.0
  share_plus: ^3.0.4
  file_picker: ^4.2.7
  cloud_firestore: ^2.5.4
  flutter_countdown_timer: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  json_serializable: ^4.1.4 
  retrofit_generator: any
  injectable_generator: any 
  logger:
    git:
      url: git://github.com/leisim/logger.git
      ref: master

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/gifs/


  fonts:
    - family: SVN Product Sans
      fonts:
        - asset: assets/fonts/SVNProductSans_Regular.ttf
        - asset: assets/fonts/SVNProductSans_Italic.ttf
          style: italic
        - asset: assets/fonts/SVNProductSans_Bold.ttf
          weight: 700
        - asset: assets/fonts/SVNProductSans_Bold_Italic.ttf
          style: italic
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
